services:
  app:
    build:
      context: .
      dockerfile: App.Dockerfile
      args:
        - SERVER_PORT=${SERVER_PORT}
        - APP_DIRECTORY=${APP_DIRECTORY}
    container_name: ${IMAGE}
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
  database:
    build:
      context: .
      dockerfile: Database.Dockerfile
    restart: always
    shm_size: 128mb
    user: ${POSTGRES_UID}:${POSTGRES_GID}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pg-data:${PGDATA}
  adminer:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=database
    restart: always
    ports:
      - 8080:8080

volumes:
  pg-data:
