CREATE TABLE users (
    id SERIAL PRIMARY KEY UNIQUE NOT NULL,
    email VARCHAR(355) UNIQUE NOT NULL,
    salt VARCHAR(256) NOT NULL,
    password VARCHAR(256) NOT NULL
);

CREATE TABLE urls (
    slug VARCHAR(256) UNIQUE NOT NULL PRIMARY KEY,
    long VARCHAR(2048) NOT NULL,
    "user" INT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    visits INT DEFAULT 0 NOT NULL
);